## settings of this model
#
#
#
#
#coTracker:
#  checkpoint_path: "./checkpoints/cotracker_stride_4_wind_8.pth"
#  output_path: "./input_output/outputs/wood/"
#
#  video_path: "./input_output/inputs/wood/N882A6_ch2_main_20221012110243_20221012110912.mp4"
#  crop_frame_y0: 400 # from
#  crop_frame_y1: 600 #  -1 to disable
#
#  mask_path: "./input_output/inputs/wood/N882A6_ch2_main_20221012110243_20221012110912/Frame_000000/mask_frame_blue_col_right_refined.png"
#  mask_strip_y0: 490 #
#  mask_strip_y1: 440 #  -1 to disable
#
#  grid_size:   500 #  default=500, help="Regular grid size"
#  grid_query_frame: 0  # default=0, help="Compute dense and grid tracks starting from this frame "
#  backward_tracking: False  # action="store_true", help="Compute tracks in both directions, not only forward",
#
